Aa #8 information button
lindakw/air-O-Meter_appRN pull request #23
Opened 2022-09-26 22:38 UTC by Amele-A

Add navigation to Index- button on Main page. when the button click it takes to the index-page.

2022-09-26 22:45 UTC, lindakw approved these changes
Everything looks good!

2022-09-26 22:46 UTC, kmausolf requested changes
I think you want to change the base branch to `development` here instead of `main`.  Also, there's a bit of overlap between your PR and Linda's from earlier.  When hers is merged, pull from `development` and push.  I'll remove the hold when the base branch is set to `development` to ensure code isn't being merged to the wrong place.

2022-09-26 22:46 UTC, kmausolf commented on screens/search_screen/search.tsx
> +  console.log(data);
Leftover console log here.

2022-09-26 22:47 UTC, kmausolf commented
Other than what was mentioned, the PR looks great!

2022-09-26 22:50 UTC, kmausolf commented
Thanks @lindakw !  Just waiting on the pull from development.

2022-09-26 23:46 UTC, kmausolf approved these changes

2022-09-27 00:14 UTC, merged

2022-09-27 00:18 UTC, Kacique reviewed
All good